### ISSUE TITLE
1.19.2 port

### ISSUE THREAD

**Issue by collatzcoder** [Endalion/trackwork#4]
Since a 1.19.2 port isnt going to be official is it ok if I make one? Do I need to do anything paperwork-wise? And If I'm clear, can you point me in the direction of how to update it?

**Comment by Endalion** [comment]
paperwork is crazy. Trackwork is MIT Licensed, and if you don't know porting workflow its best to leave it to someone that does.

**Comment by Endalion** [comment]
Closed as no updates
