### ISSUE TITLE
Wheel and Track issue

### ISSUE THREAD

**Issue by Rhaptein** [Endalion/trackwork#5]
Forge 1.20.1 1.0.1-beta, Diesiel+VS2&Clockwork mods

Wheels and Tracks can't deassemble properly. The block's physics remain but doesn't want to function.

Love this mod thank you the tracks look immaculate. It'd be awesome if this mod can spice up the survival gameplay with some smaller wheel variants? & perhaps a redstone link into the recipe of the wheel as a servo, takes building space when making smaller vehicles

**Comment by Endalion** [comment]
> Wheels and Tracks can't deassemble properly.
Disassembly is a nightmare. I recommend against doing it at all.

> The block's physics remain but doesn't want to function.
I'm sorry but this doesn't make sense to me, how can it have physics when disassembled?

> It'd be awesome if this mod can spice up the survival gameplay with some smaller wheel variants?
Planned, but far future.

> & perhaps a redstone link into the recipe of the wheel as a servo
I'm still considering how to tackle this problem. What you suggested is an ok idea (and I have thought of it) but doesn't solve a bunch of other issues that become very apparent with trackwork.

**Comment by Endalion** [comment]
Closing inactive thread
