### ISSUE TITLE
Wheels and Tracks don't work correctly on mini vehicles

### ISSUE THREAD

**Issue by Miner34dev** [Endalion/trackwork#6]
Create a vehicle with Valkyrien Skies's mini ship creator item, the put wheels/tracks on it. It will start flying around like crazy, and even the creative gravitron can have issues keeping it steady. This is even more easy to see on smaller (created using the mini ship creator multiple times) vehicles.

**Comment by Endalion** [comment]
I may support scale in the future. For now its too much effort.
