### ISSUE TITLE
Fabric port

### ISSUE THREAD

**Issue by Miner34dev** [Endalion/trackwork#7]
Is a Fabric port planned? I'm tired of having to use Forge, some of my favorite mods (like Replay mod) aren't on forge, and it would be pretty interesting to use it to create a epic tank combat video.

**Comment by Endalion** [comment]
No. I don't know how to use the fabric API and I do not have the resources to maintain a fabric port. You are welcome to ask someone else to try, there is at least one person working on one right now.
