### ISSUE TITLE
[bug] suspension losing all power when reassembling a vehicle

### ISSUE THREAD

**Issue by Hastagaspatcho** [Endalion/trackwork#9]
When disassembling then reassembling a car with the VS Eureka Mod the suspension completely breaks until the blocks for the wheels/tracks are broken and replaced. 

Create 0.5.1.f
Trackwork 1.0.1-beta
VS Eureka Mod 1.5.1-beta

**Comment by Endalion** [comment]
Disassembly is a mistake and it never should've existed
